lexer grammar CreservedWords;

OPEN_PARENTH	: '(';
CLOSE_PARENTH	: ')';
OPEN_CURL		: '{';
CLOSE_CURL		: '}';
EQUALS			: '=';
PLUS			: '+';
MINUS			: '-'; 
MULT			: '*';
DIV				: '/'; 
DOUBLE_QUOTE	: '"';
SEMI			: ';';
PRINT			: 'printf';
MAIN			: 'void main()';
CHAR			: '"'[a-zA-Z ]'"';	
INT 			: [0-9]+ ;
FLOAT 			: [0-9]+[.][0-9]+;
STRING			: '"'.+?'"';	
ID				: [a-zA-Z]([a-zA-Z0-9_]+)?;
WS				: [ \t\r\n]+ -> skip;